<?xml version="1.0"?>
<package format="3">
  <name>rover_bringup</name><version>0.1.0</version>
  <description>Top-level autonomous rover launch files.</description>
  <maintainer email="gurnek@mercedesandsingh.com">Gurnek Sandhu</maintainer><license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>rover_gazebo</exec_depend><exec_depend>rover_mission</exec_depend>
  <exec_depend>rover_navigation</exec_depend><exec_depend>rover_safety</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>

